annotations: use fun instead of function
truemedian/luvit-api-design pull request #19
Opened 2022-06-14 20:33 UTC by Bilal2453

Sumneko's language server offers the annotation `fun(arg_name: type): return_type` to annotate functions.

This PR converts most of the `function` types into that, with some exceptions to the modules where I have no clue what the arguments/returns look like.

codec.lua should be reviewed for argument names, not so sure about `data` vs `chunk`.

2022-06-14 21:43 UTC, truemedian requested changes

2022-06-14 21:43 UTC, truemedian commented on std/fs.lua
> +---@return fun(name: string, type: string)
The function this returns is an iterator, it will probably take no arguments and return `string, string`

2022-06-14 21:43 UTC, truemedian commented on std/codec.lua
> +---@alias std.codec.writer fun(data: string)
A more adequate name for this string is "buffer"

2022-06-14 22:36 UTC, Bilal2453 commented on std/fs.lua
> +---@return fun(name: string, type: string)
oops, got that reversed.

2022-06-15 19:59 UTC, truemedian approved these changes

2022-06-15 19:59 UTC, merged